# Cadence Conversion

## Input formats

nx(<list>)+mx(<list>)+...

where
n,m are positive integers
<lists> are one or more rep counts.
    
*Example*
    
1x(1,2,3) should become [1,2,3]

### Case 0:  Setup

In [155]:
import numpy as np
import pandas as pd
from os import path
import re

#dataSetPath = './Data Files/'

## Define Functions

In [165]:
# superceded
def getSeries (inStr):
    inStr.replace('*', 'x')
    if inStr.find('x') > -1:
        (mult, set) = inStr.split('x')
    else:
        # Assume that the multiplier is 1
        mult = 1
        set = inStr

    # Unidirectional Ladder
    if set.count('-->') > 0:
        (start,stop) = set.split('-->')
        start = int(start.replace('(','').replace(')',''))
        stop = int(stop.replace('(','').replace(')',''))
        if stop < start:
            step = -1
            stop -= 1
        else:
            step = 1
            stop += 1
        cadence = np.tile(np.arange(start, stop, step), int(mult))
    # Bidirectional Ladder
    elif set.count('<-->') > 0:
        #TODO
        cadence = 'NaC'
    # Malformed Set
    elif set.count(',') == 0:
        cadence = 'NaC'
    # Basic Set
    else:
        res = list(eval(set))
        cadence = np.tile(res, int(mult))
    return cadence

# not used
def parseSeries( inStr):
    listSeries = []
    if inStr.find('+') > -1:
        listSeries = (inStr.split('+'))
    else:
        listSeries.append(inStr)
    return listSeries


In [175]:

def tokenize(inStr):
    if inStr.find('+') > -1:
        return inStr.split('+')
    else:
        return [inStr]

def parseOperators(inStr):
    outList = []
    mode = 'tile'
    #inStr = inStr[0]

    if inStr.count('r') == 1:
        mode = 'repeat'
        inStr = inStr.replace('r','')

    inStr.replace('*','+')
    
    if inStr.count('x') == 0:
        # basic Set
        mult = 1
        set=inStr
    else:
        (mult, set) = inStr.split('x')

    # need to check to see if set has an operator embedded
    if set.count('-->') == 1:
        start, stop = set.split('-->')
        start = int(re.sub('\(','',start))
        stop = int(re.sub('\)','',stop))
        if stop < start:
            step = -1
            stop -= 1
        else:
            step = 1
            stop += 1
        set = np.arange(start, stop, step)
    else:
        # otherwise, evaluate set
        set = list(eval(set))

    if mode == 'tile':
        outList= np.tile(set, int(mult))
    elif mode == 'repeat':
        outList = np.repeat(set, int(mult))

    return outList


In [171]:
connStr = 'mysql+mysqldb://root:terces@0.0.0.0:3306/Activity'
df = pd.read_sql_query('Table DataFrame;',connStr)

### Case 1:  nx(<list>)

In [178]:
for cadence in df['cadence']:
    listFinal = []
    for token in tokenize(cadence):
        #print(token)
        #print(parseOperators(token))
        listFinal.extend(parseOperators(token))
    #tokens = tokenize(cadence)
    #print(tokens)
    #print(parseOperators(tokens))
    print(f"In: {cadence}\t Out: {listFinal}")

In: 1x(6,5,4,3,3)	 Out: [6, 5, 4, 3, 3]
In: 1x(3,4,7,4)	 Out: [3, 4, 7, 4]
In: 1x(4,6,10,6)	 Out: [4, 6, 10, 6]
In: 1x(4,6,10,6)	 Out: [4, 6, 10, 6]
In: 1x(6,5,4,3,3)	 Out: [6, 5, 4, 3, 3]
In: 1x(6,5,4,3,3)	 Out: [6, 5, 4, 3, 3]
In: 1x(3,4,7,4)	 Out: [3, 4, 7, 4]
In: 1x(4,6,10,6)	 Out: [4, 6, 10, 6]
In: 1x(6,5,4,3,3)	 Out: [6, 5, 4, 3, 3]
In: 1x(3,4,7,4)	 Out: [3, 4, 7, 4]
In: 1x(4,6,10,6)	 Out: [4, 6, 10, 6]
In: 1x(4,6,10,6)	 Out: [4, 6, 10, 6]
In: 1x(1,3,1,1,1)	 Out: [1, 3, 1, 1, 1]
In: 1x(1,1)	 Out: [1, 1]
In: 1x(3,4,7,3,4,6)	 Out: [3, 4, 7, 3, 4, 6]
In: 1x(3,4,7,3,4,6)	 Out: [3, 4, 7, 3, 4, 6]
In: 1x(4,6,10,4,6,10,4,6)	 Out: [4, 6, 10, 4, 6, 10, 4, 6]
In: 1x(1,3,1,1,1)	 Out: [1, 3, 1, 1, 1]
In: 1x(1,3,1,1,1)	 Out: [1, 3, 1, 1, 1]
In: 1x(3,4,7,3,4,6)	 Out: [3, 4, 7, 3, 4, 6]
In: 1x(4,6,10,4,7,10,4,6)	 Out: [4, 6, 10, 4, 7, 10, 4, 6]
In: 1x(1,3,1,1)	 Out: [1, 3, 1, 1]
In: 1x(3,4,7,3,4,6)	 Out: [3, 4, 7, 3, 4, 6]
In: 1x(4,6,10,4,7,10,4,6)	 Out: [4, 6, 10, 4, 7, 10, 4, 6]
In: 1x(4,6,10

/Users/edmundlskoviak/Documents/repos/mlpython/vpython-macos/lib/python3.9/site-packages/numpy/lib/shape_base.py:1250: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  c = _nx.array(A, copy=False, subok=True, ndmin=d)


In [44]:
# superceded
cadences = df['cadence'].to_numpy()

for indata in cadences:
    print(f"{indata}:")
    listCadence = parseSeries(indata)
    print(listCadence)

    for cadence in listCadence:
        print(cadence)
        print(f"{getSeries(cadence)}")

#    print(listCadence)
#    if indata.find('+') > -1:
#        print(indata, indata.split('+'))
#    else:  
#        print(f"In: {indata} out: {getSeries(indata)}")

1x(6,5,4,3,3):
['1x(6,5,4,3,3)']
1x(6,5,4,3,3)
[6 5 4 3 3]
1x(3,4,7,4):
['1x(3,4,7,4)']
1x(3,4,7,4)
[3 4 7 4]
1x(4,6,10,6):
['1x(4,6,10,6)']
1x(4,6,10,6)
[ 4  6 10  6]
1x(4,6,10,6):
['1x(4,6,10,6)']
1x(4,6,10,6)
[ 4  6 10  6]
1x(6,5,4,3,3):
['1x(6,5,4,3,3)']
1x(6,5,4,3,3)
[6 5 4 3 3]
1x(6,5,4,3,3):
['1x(6,5,4,3,3)']
1x(6,5,4,3,3)
[6 5 4 3 3]
1x(3,4,7,4):
['1x(3,4,7,4)']
1x(3,4,7,4)
[3 4 7 4]
1x(4,6,10,6):
['1x(4,6,10,6)']
1x(4,6,10,6)
[ 4  6 10  6]
1x(6,5,4,3,3):
['1x(6,5,4,3,3)']
1x(6,5,4,3,3)
[6 5 4 3 3]
1x(3,4,7,4):
['1x(3,4,7,4)']
1x(3,4,7,4)
[3 4 7 4]
1x(4,6,10,6):
['1x(4,6,10,6)']
1x(4,6,10,6)
[ 4  6 10  6]
1x(4,6,10,6):
['1x(4,6,10,6)']
1x(4,6,10,6)
[ 4  6 10  6]
1x(1,3,1,1,1):
['1x(1,3,1,1,1)']
1x(1,3,1,1,1)
[1 3 1 1 1]
1x(1,1):
['1x(1,1)']
1x(1,1)
[1 1]
1x(3,4,7,3,4,6):
['1x(3,4,7,3,4,6)']
1x(3,4,7,3,4,6)
[3 4 7 3 4 6]
1x(3,4,7,3,4,6):
['1x(3,4,7,3,4,6)']
1x(3,4,7,3,4,6)
[3 4 7 3 4 6]
1x(4,6,10,4,6,10,4,6):
['1x(4,6,10,4,6,10,4,6)']
1x(4,6,10,4,6,10,4,6)
[ 4  6 10  4  6 10  4 

/Users/edmundlskoviak/Documents/repos/mlpython/vpython-macos/lib/python3.9/site-packages/numpy/lib/shape_base.py:1250: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  c = _nx.array(A, copy=False, subok=True, ndmin=d)


ValueError: invalid literal for int() with base 10: '5,3,2,7'

In [36]:
row, col = df.shape
print (row, col)

63 1


In [70]:
listL = []
rem = ''
start = 0
while len(helper) > 0:
    stop = helper.find('x')
    if stop == -1:
        listL.append(helper[start:])
        helper = ''
    else:
        listL.append(helper[start:stop-2])
        start = stop-1
        helper = helper[start:]
        break

print(listL, helper)

['5,3,2', '7x(1,)']
['5,3,2'] 7x(1,)


In [99]:
def tokenize(inStr):
    if inStr.find('+') > -1:
        return inStr.split('+')
    else:
        return [inStr]

def parseOperators(inStr):
    outList = []
    inStr.replace('*','+')
    if inStr.count('x') == 0:
        # basic Set
        outList=list(eval(inStr))
    
    if inStr.count('x') == 1:
        # in  n x (...)[t | r]  default to t
        mode = 'tile'
        if inStr.count('r') == 1:
            mode = 'repeat'
            inStr = inStr.replace('r','')
        (mult, set) = inStr.split('x')
        if mode == 'tile':
            outList= np.tile(list(eval(set)), int(mult))
        elif mode == 'repeat':
            outList = np.repeat(list(eval(set)), int(mult))

    return outList
 
helper = '2x(5,3,2)+2x(1,3)'
#print(tokenize(helper))
#print(parseOperators(tokenize(helper)[0]))
listFinal = []
for token in tokenize(helper):
    listFinal.extend(parseOperators(token))
    print(parseOperators(token))

print(listFinal)

[5 3 2 5 3 2]
[1 3 1 3]
[5, 3, 2, 5, 3, 2, 1, 3, 1, 3]


In [119]:
import re
i = '(1,)'
re.sub('\(','',i)
#i = i.replace('()','')
#print(int('(1'))

'1'

In [148]:
i = '(1,2,3)'
eval(i)
list(eval(i))
y = (1,2,4)
list(y)

[1, 2, 4]